name: Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1
            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  github-comment: false
                  vercel-args: "--prod"
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_SCOPE }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  scope: ${{ secrets.VERCEL_SCOPE }}
